### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by aatishb** [aatishb/springtuning#1]
Next steps: 

- [ ] Support multiple octaves
- [ ] Spring colors to denote whether stretched or compressed
- [ ] Possibly introduce wraparound springs
